apiVersion : apps/v1
kind: Deployment
metadata:
  name: evansdockerglpidb 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evansdockerglpidb
  template:
    metadata:
      labels:
        app: evansdockerglpidb 
    spec:
      containers:
        - name: evansdockerglpidb 
          image: eforder.azurecr.io/evansdockerglpidb
          ports:
          - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: pas